version: '3'
volumes:
  dados:
  nosql:
networks:
  banco:
  app:
services:
  node:
    build: .
    volumes:
      - .:/app
    command: yarn start
    environment:
      DB_HOST: db
      DB_SECRET: passwordDB
    ports:
      - '3333:3333'
    depends_on:
      - db
      - mongo
    networks:
      - banco
      - app
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - dados:/var/lib/postgresql/data
      - ./db:/scripts
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: passwordDB
    networks:
      - banco
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - banco
